export interface ProviderPreset {
  id: string;
  name: string;
  baseUrl: string;
  models: string[];
  apiKeyUrl?: string;
  category: 'domestic' | 'aggregator' | 'third-party' | 'research' | 'local';
  categoryLabel: string;
}

export const PROVIDER_PRESETS: ProviderPreset[] = [
  // 国内厂商
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    models: ['deepseek-v4-pro', 'deepseek-v4-flash', 'deepseek-chat'],
    apiKeyUrl: 'https://platform.deepseek.com',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    models: ['glm-5', 'glm-4-plus', 'glm-4-flash'],
    apiKeyUrl: 'https://open.bigmodel.cn',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'zhipu-intl',
    name: '智谱 GLM 国际',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    models: ['glm-5', 'glm-4-plus'],
    apiKeyUrl: 'https://z.ai',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'qwen',
    name: '阿里百炼 (通义千问)',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    models: ['qwen3-coder-plus', 'qwen3-max', 'qwen-plus'],
    apiKeyUrl: 'https://bailian.console.aliyun.com',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'kimi',
    name: 'Kimi (月之暗面)',
    baseUrl: 'https://api.moonshot.cn/v1',
    models: ['kimi-k2.6', 'moonshot-v1-auto'],
    apiKeyUrl: 'https://platform.moonshot.cn',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'stepfun',
    name: 'StepFun (阶跃星辰)',
    baseUrl: 'https://api.stepfun.ai/v1',
    models: ['step-3.5-flash', 'step-2-16k', 'step-1-8k'],
    apiKeyUrl: 'https://platform.stepfun.ai',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    baseUrl: 'https://api.minimaxi.com/v1',
    models: ['MiniMax-M2.7', 'abab7-chat'],
    apiKeyUrl: 'https://platform.minimaxi.com',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'minimax-intl',
    name: 'MiniMax 国际',
    baseUrl: 'https://api.minimax.io/v1',
    models: ['MiniMax-M2.7'],
    apiKeyUrl: 'https://platform.minimax.io',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'mimo',
    name: '小米 MiMo',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    models: ['mimo-v2.5-pro', 'mimo-v2.5-flash'],
    apiKeyUrl: 'https://platform.xiaomimimo.com',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'mimo-token',
    name: '小米 MiMo Token Plan',
    baseUrl: 'https://token-plan-cn.xiaomimimo.com/v1',
    models: ['mimo-v2.5-pro', 'mimo-v2.5-flash'],
    apiKeyUrl: 'https://platform.xiaomimimo.com',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },
  {
    id: 'longcat',
    name: 'Longcat',
    baseUrl: 'https://api.longcat.chat/openai/v1',
    models: ['LongCat-Flash-Chat', 'LongCat-Flash'],
    apiKeyUrl: 'https://longcat.chat/platform',
    category: 'domestic',
    categoryLabel: '国内厂商',
  },

  // 聚合平台
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn/v1',
    models: ['Pro/MiniMaxAI/MiniMax-M2.7', 'Qwen/Qwen3-Coder-480B-A35B-Instruct', 'deepseek-ai/DeepSeek-V3'],
    apiKeyUrl: 'https://siliconflow.cn',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'siliconflow-intl',
    name: 'SiliconFlow 国际',
    baseUrl: 'https://api.siliconflow.com/v1',
    models: ['MiniMaxAI/MiniMax-M2.7', 'Qwen/Qwen3-Coder-480B-A35B-Instruct'],
    apiKeyUrl: 'https://siliconflow.com',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    models: ['anthropic/claude-opus-4-7', 'openai/gpt-5.4', 'google/gemini-2.5-pro'],
    apiKeyUrl: 'https://openrouter.ai',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'therouter',
    name: 'TheRouter',
    baseUrl: 'https://api.therouter.ai/v1',
    models: ['openai/gpt-5.4', 'anthropic/claude-opus-4-7'],
    apiKeyUrl: 'https://therouter.ai',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'together',
    name: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    models: ['Qwen/Qwen3-Coder-480B-A35B-Instruct', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct'],
    apiKeyUrl: 'https://together.ai',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'novita',
    name: 'Novita AI',
    baseUrl: 'https://api.novita.ai/v3/openai',
    models: ['zai-org/glm-5', 'deepseek-ai/DeepSeek-V3'],
    apiKeyUrl: 'https://novita.ai',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'aihubmix',
    name: 'AiHubMix',
    baseUrl: 'https://aihubmix.com/v1',
    models: ['gpt-5.4', 'claude-opus-4-7'],
    apiKeyUrl: 'https://aihubmix.com',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'dmxapi',
    name: 'DMXAPI',
    baseUrl: 'https://www.dmxapi.cn/v1',
    models: ['gpt-5.4', 'claude-opus-4-7'],
    apiKeyUrl: 'https://www.dmxapi.cn',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'modelscope',
    name: 'ModelScope (魔搭)',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    models: ['ZhipuAI/GLM-5', 'Qwen/Qwen3-Coder-480B-A35B-Instruct'],
    apiKeyUrl: 'https://modelscope.cn',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'compshare',
    name: 'Compshare (算力共享)',
    baseUrl: 'https://api.modelverse.cn/v1',
    models: ['gpt-5.4', 'claude-opus-4-7'],
    apiKeyUrl: 'https://www.compshare.cn',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'compshare-coding',
    name: 'Compshare Coding Plan',
    baseUrl: 'https://cp.compshare.cn/v1',
    models: ['gpt-5.4', 'claude-opus-4-7'],
    apiKeyUrl: 'https://www.compshare.cn',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'shengsuanyun',
    name: 'Shengsuanyun (胜算云)',
    baseUrl: 'https://router.shengsuanyun.com/api/v1',
    models: ['openai/gpt-5.4', 'anthropic/claude-opus-4-7'],
    apiKeyUrl: 'https://www.shengsuanyun.com',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    baseUrl: 'https://integrate.api.nvidia.com',
    models: ['moonshotai/kimi-k2.5', 'qwen/qwen3-coder'],
    apiKeyUrl: 'https://build.nvidia.com',
    category: 'aggregator',
    categoryLabel: '聚合平台',
  },

  // 第三方
  {
    id: 'lemondata',
    name: 'LemonData',
    baseUrl: 'https://api.lemondata.cc/v1',
    models: ['gpt-5.4', 'gpt-4o'],
    category: 'third-party',
    categoryLabel: '第三方',
  },
  {
    id: 'pateway',
    name: 'PatewayAI',
    baseUrl: 'https://api.pateway.ai',
    models: ['gpt-4o', 'gpt-4o-mini'],
    category: 'third-party',
    categoryLabel: '第三方',
  },

  // 研究机构
  {
    id: 'nous',
    name: 'Nous Research',
    baseUrl: 'https://inference-api.nousresearch.com/v1',
    models: ['Hermes-4-405B', 'DeepHermes-4-Mid'],
    category: 'research',
    categoryLabel: '研究机构',
  },

  // 本地 / 自部署
  {
    id: 'ollama',
    name: 'Ollama',
    baseUrl: 'http://localhost:11434/v1',
    models: [],
    category: 'local',
    categoryLabel: '本地 / 自部署',
  },
  {
    id: 'vllm',
    name: 'vLLM',
    baseUrl: 'http://localhost:8000/v1',
    models: [],
    category: 'local',
    categoryLabel: '本地 / 自部署',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    baseUrl: 'http://localhost:1234/v1',
    models: [],
    category: 'local',
    categoryLabel: '本地 / 自部署',
  },
];

export function getProviderById(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((p) => p.id === id);
}
